# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citadel', '0002_auto_20160227_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankingdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='bankingdetails',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankingdetails',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankingdetails',
            name='surname',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsmessage',
            name='title',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankingdetails',
            name='Balance',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
